[package]
name = "checkout-kata-in-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.25"
rust_decimal_macros = "1.25"
mockall = "0.11.1"